[package]
name = "jsonschema-to-dhall"
version = "0.1.0"
authors = ["Brandon Kase <brandon.kase@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.7.2"
serde = "1.0"
serde_json = "1.0"
